### ISSUE TITLE
Makeability Lab *TEST* server showing up in Google search results

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#1000]
![image](https://user-images.githubusercontent.com/1621749/157448830-185a2519-af71-40ec-a7a9-49bc08c6f5cc.png)

We need to add a `robots.txt` file to test (but not to production).

From reading about this, it seems like the file should simply say:

> User-agent: * Disallow: /

Some directions from Google: https://developers.google.com/search/docs/advanced/robots/create-robots-txt#:~:text=txt%20file.-,The%20robots.,.com%2Frobots.txt%20.

And moz: https://moz.com/learn/seo/robotstxt

**Comment by mechanicjay** [comment]
This is complete.  I've placed the file at /cse/web/research/makelab/www-test/robots.txt and made an alias on the -test webserver to serve that up.
https://makeabilitylab-test.cs.washington.edu/robots.txt

**Comment by mechanicjay** [comment]
hrmph.  It's evaluating correctly for https, but not http.    This might be a limitation of the testers?  The RFC (and google's documentation) says it'll follow 5 redirect hops before treating the file as 404.

**Comment by misaugstad** [comment]
I've been reading up a bit on how to prevent sites from being shown in search engines, and it doesn't seem like the robots.txt file and preventing indexing is the thing that needs to be done.

From [this link](https://yoast.com/prevent-site-being-indexed/):
![x-robots-tag](https://user-images.githubusercontent.com/6518824/157524315-c8e4fd6a-1f6a-4149-b100-37276e987152.png)

@mechanicjay is this something that you could do? And does this look like a real solution to you? 

Another link with more concrete steps but less explanation of why: https://www.ilfusion.com/how-to-prevent-google-from-indexing-certain-web-pages#:~:text=1.,shown%20in%20search%20engine%20results.

**Comment by jonfroehlich** [comment]
I have no experience with this so I personally don't know what is best. I thought this would be sufficient:

![image](https://user-images.githubusercontent.com/1621749/157720882-a44fc696-7208-4378-a2d1-2c51a1d830a7.png)

**Comment by jonfroehlich** [comment]
Looks like this is now fixed!

![image](https://user-images.githubusercontent.com/1621749/163652223-bad0ae8a-95f4-4862-ab69-d2f681c86c58.png)

I believe @mechanicjay fixed it by using @misaugstad's proposed solution:
https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1000#issuecomment-1063315541

**Comment by misaugstad** [comment]
Okay I don't actually think that it's fully working :/ If you look at the second link below, it still points to the test server. And for Project Sidewalk, the Amsterdam test server is still the only one showing up at the top :pensive: 
![Screenshot from 2022-04-19 10-35-15](https://user-images.githubusercontent.com/6518824/164062819-f9ddfa60-df7a-4de1-9793-74366122d995.png)
![Screenshot from 2022-04-19 10-35-30](https://user-images.githubusercontent.com/6518824/164062823-967d5a54-49e3-4681-b460-fcfb15412e3b.png)

**Comment by jonfroehlich** [comment]
Ugh, oh no!

**Comment by mechanicjay** [comment]
The file is valid, and the testers evaluate it properly for https, but 
don't respect it for http -- not sure what's going on there yet, will 
look into it.

--Jason

**Comment by jonfroehlich** [comment]
I think it's working now:

![image](https://user-images.githubusercontent.com/1621749/199114079-c4dab4af-721d-4fde-bdce-11507f3f5dd9.png)

![image](https://user-images.githubusercontent.com/1621749/199114111-d5286120-fe1a-4720-a532-d3af5f066364.png)

Thanks @mechanicjay and @misaugstad
