### ISSUE TITLE
How is this "street has no sidewalks" tag possible?

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#1005]
The "street has no sidewalks" tag doesn't exist for the "Surface Problem" label type (but rather for the "Missing Sidewalk" label type). Not sure how this is possible:

![image](https://user-images.githubusercontent.com/1621749/173423044-98674bb5-02d1-4791-b0bf-256b1c0f6b5a.png)

**Comment by misaugstad** [comment]
Fixed, described [here](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2844).
