### ISSUE TITLE
Multiple objects can be added due to the long uploading time

### ISSUE THREAD

**Issue by xiasu** [makeabilitylab/makeabilitylabwebsite#1012]
I laughed loud when I saw this in the HoloSound project page:
![image](https://user-images.githubusercontent.com/61726267/195517770-fef6a3a4-d95b-4610-bac4-18920a36aa45.png)
I came across similar issue when I was adding project roles to people. It's very easy to click the save button multiple times since it takes a few seconds for the webpage to respond. But each click during this seemingly frozen time could independently add the same content, resulting in multiple duplicates of content shown on webpage.
![image](https://user-images.githubusercontent.com/61726267/195518534-09a15787-10ae-4edc-aba1-b91e3aa670b8.png)

**Comment by xiasu** [comment]
Systematically solving this bug might not be very straightforward, but at least we could use some more double checking. This HoloSound page is already fixed now.

**Comment by jonfroehlich** [comment]
Interesting. Thanks @xiasu.

**Comment by jonfroehlich** [comment]
@xiasu Can you explain how this bug occurred? Did you upload the same talk multiple times? I've never had an issue w this.
