### ISSUE TITLE
Backend Panels Gone after Upgrading

### ISSUE THREAD

**Issue by xiasu** [makeabilitylab/makeabilitylabwebsite#1021]
After upgrading our Django framework version to the latest, I noticed some panels in the backstage page are gone. Two examples I noticed are:

1. "Add Project Role" Panel in People page
![image](https://user-images.githubusercontent.com/61726267/200708707-be85fc53-9fdc-4329-b09f-e4ffc0b12697.png)
2. "Add other visualization" panel in project page. 

These missing panels make us unable to upload some key information, thus cannot show up new projects.

**Comment by jonfroehlich** [comment]
I was expecting to wake up this morning and quickly fix this, but I need more information. I'm not seeing the problems you're articulating. I don't think we ever had language that said "Add other visualization". Perhaps you mean something else?

1. I'm not seeing this problem. For me, Project Roles shows up fine on the add person page:
https://makeabilitylab.cs.washington.edu/admin/website/person/add/
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/1621749/200842377-fe7ac342-f7e4-4083-b7cd-93278f554479.png">

2. For "Add other visualization" panel. I'm not sure what you mean. 
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/1621749/200842647-48f273cf-07ef-45de-a596-b3812a03c290.png">

Also, Daniel's page appears to show just fine:
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/1621749/200843285-0d0f0cb0-b86c-4beb-80e4-d15dc0eb50f5.png">

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/1621749/200843364-7f842abe-f07e-4ff9-b67a-3d2c9ec4bc84.png">

**Comment by xiasu** [comment]
Turns out the issue is caused by logging in with gradmin, instead of makeadmin. The gradmin account has less user permissions thus cannot access these panels. For later use, please avoid using this account.
