### ISSUE TITLE
Need to add Director to position choices

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#1115]
Should also switch these selections to Django Choices on backend

<img width="555" alt="image" src="https://github.com/makeabilitylab/makeabilitylabwebsite/assets/1621749/f22ba19a-68df-46a1-a6fc-0f00b6000dfb">

**Comment by VidyaYadavv1519** [comment]
can you explain more what exactly you want ??

**Comment by jonfroehlich** [comment]
Now added!

<img width="662" alt="image" src="https://github.com/makeabilitylab/makeabilitylabwebsite/assets/1621749/72fe4950-3e8a-476b-865f-d76ae9c14b0a">
