### ISSUE TITLE
Twitter and Github logo icons are broken in footer

### ISSUE THREAD

**Issue by misaugstad** [makeabilitylab/makeabilitylabwebsite#1124]
In the footer, the Github and Twitter icons are just showing up as an X in a box.

![Screenshot from 2024-01-17 11-48-14](https://github.com/makeabilitylab/makeabilitylabwebsite/assets/6518824/23233f1c-5991-49fd-86b2-e9fd1eff989c)

**Comment by jonfroehlich** [comment]
Thanks @misaugstad. Too bad Twitter is now actually an X. 😂

#elonruinedtwitter
