### ISSUE TITLE
All images on Makeability Lab website are broken

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#1149]
I did not push any new code so not sure what is happening.

![image](https://github.com/makeabilitylab/makeabilitylabwebsite/assets/1621749/9c0b42ad-73a5-4865-8ab8-3552cd690aef)

![image](https://github.com/makeabilitylab/makeabilitylabwebsite/assets/1621749/9f5b4e43-84c7-4d2d-85e8-6e1c13e6d6c4)

**Comment by hoominchu** [comment]
Two things I found out so far—
1. The 'img' tags are missing the 'src' attribute.
<img width="588" alt="Screenshot 2024-05-03 at 9 38 03 AM" src="https://github.com/makeabilitylab/makeabilitylabwebsite/assets/8168506/1fd555a2-c9db-4050-aa3d-0780d8919b9c">

2. These 'could' be the relevant errors (not sure)
<img width="956" alt="Screenshot 2024-05-03 at 9 38 23 AM" src="https://github.com/makeabilitylab/makeabilitylabwebsite/assets/8168506/6ec20037-5f38-455e-9c97-a3b3c04a6b6a">
<img width="956" alt="Screenshot 2024-05-03 at 9 38 59 AM" src="https://github.com/makeabilitylab/makeabilitylabwebsite/assets/8168506/bb01286b-b077-4580-83b3-7b5cd595d915">

**Comment by jonfroehlich** [comment]
Thanks @hoominchu! Matt Broadhead fixed it! Here's what he said:

> Early this morning, the filesystem backing /cse/web/research was upgraded, which made NFS mounts pointing to it have stale file handles.  I remounted the NFS mount, then restarted the docker container.
