### ISSUE TITLE
There are Two James Fogarty Names

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#209]
There are two "James Fogarty" names. When we fix this, need to make sure we merge the data that these two objects are pointing to:

![image](https://cloud.githubusercontent.com/assets/1621749/21103185/6844e8a4-c04f-11e6-83f3-493407681295.png)

**Comment by aileenzeng** [comment]
@jonfroehlich 

The current publication associated with James, Fogarty is iLearn on the iPhone: Real-Time Human Activity Classification on Commodity Mobile Phones. Right now it links to this PDF: https://makeabilitylab-test.cs.washington.edu/media/publications/iLearn_on_the_iPhone_Real-Time_Human_Activity_Classification_on_Commodity_Mobile_Phones_1tOdj6X.pdf

I was wondering if you want it to link to the paper instead? I found it online here: https://www.microsoft.com/en-us/research/wp-content/uploads/2016/12/UW-CSE-08-04-02.pdf

**Comment by jonfroehlich** [comment]
Nice catch. Yes, the microsoft PDF is the right one.
