### ISSUE TITLE
Website loading is kinda slow. 

### ISSUE THREAD

**Issue by higherdefender** [makeabilitylab/makeabilitylabwebsite#292]
Especially the landing page was really slow, when I was, say, in India (moderate connection speed). Is that a framework problem, or we could do some optimization?

**Comment by lstearns86** [comment]
While there could be other causes and we should definitely look into it, I
think the most likely problem is the many high resolution images used for
the banner and elsewhere on the page. I have a similar problem on my
personal site. Maybe we should do something like load the page first, and
then use javascript to load and populate the banner images and other hi-res
images in the background.

**Comment by jonfroehlich** [comment]
I like that idea @lstearns86. We should run some speed tests on our site (there are free externals tools for this) to help us optimize that.

Thanks @higherdefender for noting this important problem.

**Comment by higherdefender** [comment]
@jonfroehlich Yep, I could use some.

**Comment by higherdefender** [comment]
@lstearns86 Actually, the videos are getting loaded after the page. A quick page source shows the javascript for that. Not sure about the banner images though.

**Comment by jonfroehlich** [comment]
You shouldn't use the current page as for evaluation since the whole thing got redesigned recently but is not deployed to UMD. Only way to run newest source is locally on your machine.

**Comment by higherdefender** [comment]
yeah, that's fine. We could do it once it's up and running.

Pax vobiscum,
dhruvjain.info

Good emailing strategies, please read this
<http://thinksimplenow.com/productivity/15-tips-for-writing-effective-email/>
.

**Comment by jonfroehlich** [comment]
@higherdefender, any updates on this?

**Comment by higherdefender** [comment]
I think I'll do this after we've some of the 505 issues resolved.

**Comment by jonfroehlich** [comment]
Closing in favor of https://github.com/makeabilitylab/makeabilitylabwebsite/issues/959
