### ISSUE TITLE
Improved Carousel Admin

### ISSUE THREAD

**Issue by lstearns86** [makeabilitylab/makeabilitylabwebsite#38]
Since we're using a responsive design for the carousel images, it's not entirely clear how we should handle it on the admin side to make sure that we're choosing good images that won't appear overly cropped on different screen sizes. Does anyone have any suggestions?

We should explore this for a future update, but for now you should just check how the image appears on the actual site for different window sizes.

**Comment by jonfroehlich** [comment]
I updated the admin interface to give the user a better sense of the banner and cropping. But the best way to see how it looks is still to try it and view it on the actual page.
