### ISSUE TITLE
Project Page: Isotopify Talks on Project Page and Personnel Pages?

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#545]
Should we isotopify talks part of the project page with the header being years (e.g., 2018 (number) / 2017 (number) / 2016 (number)). We should do this once we snippify talks.

![image](https://user-images.githubusercontent.com/1621749/43853738-d1f0c2f0-9af5-11e8-8a0c-1dc49c75791d.png)

**Comment by johnsonkuang** [comment]
We could, I think that would look pretty good

**Comment by jonfroehlich** [comment]
Talks are now snippified, so this is possible.

**Comment by jonfroehlich** [comment]
I think this is a nice idea but I want to move away from using external libraries... it makes things more complicated and adds dependencies
