### ISSUE TITLE
Add in projects to publication listing

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#627]
![image](https://user-images.githubusercontent.com/1621749/46508505-adff4180-c7f2-11e8-9548-7a2fc981b17b.png)

**Comment by jonfroehlich** [comment]
Need to mockup some ideas about how to do this. @htadeusiak, this is a more design-oriented task if you want to give it a try...

**Comment by htadeusiak** [comment]
@jonfroehlich do you still want me to tackle this. I feel like this could be a good first project for Ketaki.

**Comment by jonfroehlich** [comment]
Sure. I’d want to see mocks first.

**Comment by jonfroehlich** [comment]
This is now done and unified throughout the website through shared code

![image](https://github.com/makeabilitylab/makeabilitylabwebsite/assets/1621749/5964505d-ee0c-47b5-a8f4-ffe866b7fb85)
