### ISSUE TITLE
Consider renaming 'FAQ' page?

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#711]
Is 'FAQ' a good name for this new page? Or should it be 'About Us'? Or something else?

**Comment by aileenzeng** [comment]
I think FAQ is nice if there’s information on the page that isn’t lab specific (an example would be the section on advice for PhD students at UMD on your old site). Otherwise, I think “About Us” sounds nice!

**Comment by jonfroehlich** [comment]
All FAQ stuff is now captured in the Makeability Lab handbook: https://docs.google.com/document/d/1YiiDsfpiolpXjUTj8xWrQwQQUzqrfqT9bocOpaYDrtI
