### ISSUE TITLE
Django'fy FAQ page

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#724]
Once I finish writing some initial content and @htadeusiak finishes the design, we'll want to loop around and Django'fy the FAQ page. I think the FAQ model will have at least the following fields:

- Question (the title)
- Short url (for anchor)--though this could be auto-generated by title and maybe this is better
- Response (rich text, if possible, see: https://github.com/jonfroehlich/makeabilitylabwebsite/issues/35)
- Date written or modified
- Maybe author? (though we could have multiple authors per post...)

**Comment by htadeusiak** [comment]
I want to get the CKEditor up and working on the website before I start working on this, I'll work with Jason on it if thats good with you.

**Comment by jonfroehlich** [comment]
Sounds good!

**Comment by htadeusiak** [comment]
After speaking with Jon I'm un-assigning my self from this issue. I never got around to it because the rich text editor was not installed. I recommend attempting this issue after CKEditor is installed on the production site.

**Comment by jonfroehlich** [comment]
And @johnsonkuang is now working on integrating the CKEditor, so we can loop around to this after that.

**Comment by jonfroehlich** [comment]
All FAQ stuff is now captured in the Makeability Lab handbook: https://docs.google.com/document/d/1YiiDsfpiolpXjUTj8xWrQwQQUzqrfqT9bocOpaYDrtI
