### ISSUE TITLE
Issue installing Docker -  Permission denied: '/code/media/debug.log'

### ISSUE THREAD

**Issue by ketakideuskar** [makeabilitylab/makeabilitylabwebsite#803]
While installing Docker, I had an issue when running `make makemigrations`. I keep running into this error - `Permission denied: '/code/media/debug.log'`. When I looked at the permissions for the /code/media folder in the docker shell, I found: `drwxr-xr-x  1   1000 staff   170 Apr 11 23:56 media`. However, all of the other files look like they are owned by apache (ex: `-rw-r--r--  1 apache root  39183 Mar 23 20:23 README.md`). Aileen and I tried changing the permissions and owners within the docker shell, but nothing seemed to change and `make makemigrations` doesn't work.

@mechanicjay any thoughts?

**Comment by jonfroehlich** [comment]
Closing because we have likely solved this with newer Docker instructions and WSL2, etc.
