### ISSUE TITLE
ValueError: Unable to configure handler 'file'

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#815]
I was attempting to test @johnsonkuang's new Docker changes (#366) but I ran into a problem on the `docker exec -it makeabilitylabwebsite_website_1 bash` step. I received a `ValueError: Unable to configure handler 'file'`--which is triggered by how we are configuring our logger. Full error message below. @johnsonkuang, have you seen this?

```
PS C:\Git\makeabilitylabwebsite> docker exec -it makeabilitylabwebsite_website_1 bash
apache@3b042774cce7:/code$ python manage.py createsuperuser
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/config.py", line 555, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/lib/python3.7/logging/config.py", line 728, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/lib/python3.7/logging/handlers.py", line 147, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.7/logging/handlers.py", line 54, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1041, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1070, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/code/media/debug.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.7/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/local/lib/python3.7/logging/config.py", line 792, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.7/logging/config.py", line 563, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'file'
```

I

**Comment by johnsonkuang** [comment]
Yes, it has to do with a volume mount that doesn’t actually exist in the development environment. I believe we’ll have to communicate with Jason on maintaining separate docker-compose files or set the volume mount somewhere else.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jonfroehlich** [comment]
OK... but in the short term, how should I get my local dev environment setup? Should I comment out the logging support? What did you do?

**Comment by johnsonkuang** [comment]
I resolved the issue by removing the mount from the docker compose file. It should be the volumes section of the website service and should contain /code/media/debug.log

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jonfroehlich** [comment]
Not sure I understand. Can you provide more detailed step-by-step instructions to fix this on the local dev environment?

**Comment by johnsonkuang** [comment]
website:    
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '127.0.0.1:8571:8000'
    volumes:
      - .:/code
      - /cse/web/research/makelab/www-test:/code/media << delete this line

**Comment by jonfroehlich** [comment]
OK, this worked. I commented it out with the `#` sign.

I'm keeping this Issue open because we need a better solution to support logging on localhost in dev environments.

**Comment by sherlinekinyanjui** [comment]
Create the following files in the directory(:/var/www/logs/projectname)  drive of where your project is located
Example, if the project's name is Towns and is located in drive D, go to drive D and create a new folder var and in that www in that logs then the project name. In my case,  D:/var/www/logs/Towns

**Comment by jonfroehlich** [comment]
@sherlinekinyanjui: I'm not sure how to use your advice. We are trying to access a Docker volume at: `/cse/web/research/makelab/www:/code/media`

**Comment by unknownArtist** [comment]
does anyone figured it out yet ?

**Comment by jonfroehlich** [comment]
No :(

**Comment by jonfroehlich** [comment]
This is now fixed with our new docker-compose setup.
