### ISSUE TITLE
Remove reference to letters of rec in ugrad research FAQ

### ISSUE THREAD

**Issue by misaugstad** [makeabilitylab/makeabilitylabwebsite#945]
We no longer use a letter of recommendation as part of the application process for undergrads, so we should remove that step from the FAQ.

**Comment by jonfroehlich** [comment]
All FAQ stuff is now captured in the Makeability Lab handbook: https://docs.google.com/document/d/1YiiDsfpiolpXjUTj8xWrQwQQUzqrfqT9bocOpaYDrtI
