### ISSUE TITLE
On People or project pages, we are not showing those with title=uncategorized

### ISSUE THREAD

**Issue by misaugstad** [makeabilitylab/makeabilitylabwebsite#952]
I wanted to add Ilia to the ML site. They will be an MS HCDE student in the fall, but they are currently a landscape architect who is working in a product design role for Project Sidewalk, which means that they don't fit well into the MS Student, Research Scientist, or Software Developer titles. I tried to give them the Uncategorized title, but then they didn't show up on the People page or the project page for Sidewalk.

Unless uncategorized is being used for something else, we should probably be including them on the People and project pages :) Maybe we need more options for Title as well :wink:

**Comment by jonfroehlich** [comment]
This is now fixed and deployed. Thanks @misaugstad!
