### ISSUE TITLE
Makeability Lab website slow to load

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#959]
Need to checkin with Jason (@mechanicjay) about it.

Updating with more search terms: lag, latency, slow load times.

Also related to https://github.com/makeabilitylab/makeabilitylabwebsite/issues/292

**Comment by jonfroehlich** [comment]
This continues to be an issue. Needs to be a priority once I find the time.

![image](https://user-images.githubusercontent.com/1621749/149008942-86a78bd1-6cd0-4d9b-8ce8-c2e8ff8e6b8a.png)

**Comment by jonfroehlich** [comment]
Ed Lazowska just emailed me and said the same thing:

> [makeabilitylab.cs.washington.edu](http://makeabilitylab.cs.washington.edu/) takes forever to load, as do the
 pages anchored by the tabs at the top of the page (Jon).

**Comment by mechanicjay** [comment]
The machine that this docker container runs on currently has 24 cores, and 128G of RAM.

RAM is approximately 50% committed, load average on this box seems to hang out between .5 and 1.5

When running TOP on the host while loading webpages, I see the django process burning 100% cpu (One full core) and the postgres container burning about 20% of a core.  

I believe this indicates some inefficiency in the code or perhaps the database routines.


As an addendum, this same hardware is running **all** the sidewalk instances.  Are you seeing performance issues there?  As another datapoint, I'm not seeing performance issues with the couple of apps I run for support on this system.

**Comment by jonfroehlich** [comment]
Thanks @mechanicjay. The code has been piecemealed together for years (since I was at UMD) so I'm not too surprised to hear that. :(

I'll have to investigate this over the summer when my time opens up a bit.

**Comment by mechanicjay** [comment]
I'm going to do a little bit of db profiling to see if anything jumps out there we might be able to address for a quick win.

**Comment by jonfroehlich** [comment]
That would be awesome. Thanks!

**Comment by mechanicjay** [comment]
Using the Sidewalk page as an example, The database is servicing a number of queries, mostly related to pulling back the associated people and papers associated.   Each of those queries is returned very quickly.  Additionally, I don't see any big queries holding up the works.  I hate to say it, but I think it's just a bottleneck in the front-end somewhere.

**Comment by jonfroehlich** [comment]
Ugh. Thanks for your help with this. I've not done frontend profiling before.

Just experimented with Chrome's profiler on our [People page](https://makeabilitylab.cs.washington.edu/people/). Doesn't look awesome. But not necessarily for full source of delays.

![image](https://user-images.githubusercontent.com/1621749/162046285-3c2ba852-e5b6-477a-9130-b71d47b20423.png)

**Comment by jonfroehlich** [comment]
We now have a Django profiler/debugger instead on makeabilitylab-test and localhost.

This is using the Django recommended [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar/):
> [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar/) is a very handy tool that provides insights into what your code is doing and how much time it spends doing it. In particular it can show you all the SQL queries your page is generating, and how long each one has taken.

![image](https://github.com/makeabilitylab/makeabilitylabwebsite/assets/1621749/9c9a8f18-3d00-482f-ba3a-bdf3b7ff32e7)

**Comment by jonfroehlich** [comment]
In addition, I added some logging statements to track things on production, and it looks like calculating position roles like `get_latest_position()` in `person.py` is very slow.

For example, for ARMath, it took 0.076 secs to render the ARMath project page but 0.056 secs of that was calculating position roles (73%). Similarly, for HandSight, it took 0.25 secs to render the project page but 0.24 secs of that was calculating position roles (over 91%). For SoundWatch: rendered in 0.12 secs but 0.10 secs was position roles (85%) and so on.

It's bad on people page or anywhere else we call that method.

**Comment by jonfroehlich** [comment]
Django's webpage has lots of resources on how to speed things up. They caution the use of relying on caching when just better, more optimal code would work.

- See [the Performance and Optimization page](https://docs.djangoproject.com/en/4.2/topics/performance/)
- Adding a [@cached_property](https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.functional.cached_property) decoratory might work well for us in some cases (like get_latest_position)

**Comment by jonfroehlich** [comment]
We are systematically shifting as many queries as possible to using Django ORM rather than Python-based filtering. Should have been doing that from the beginning.

**Comment by jonfroehlich** [comment]
Our pages are now far faster. I haven't fully converted all backend queries to ORM but we're close.

Some timings:
* People page now loads in ~0.088 secs after rewriting backend queries and only showing images for current members
* Landing page now loads in 0.033 secs with query optimization

Project pages still take too long. For example:
* [Project Sidewalk webpage](https://makeabilitylab.cs.washington.edu/project/sidewalk/) takes 0.402 secs to render
