### ISSUE TITLE
Consider smaller thumbnails or other option for listing alumni

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#991]
Now that we've had so many people work in our lab over the years, consider smaller thumbnails or other option for listing alumni

**Comment by jonfroehlich** [comment]
The Creative Interactions Lab does this:

![image](https://user-images.githubusercontent.com/1621749/199971822-7aba6f65-ea6d-4dfc-944f-568df6e48047.png)

![image](https://user-images.githubusercontent.com/1621749/199971868-10b6699e-3cc1-4ce9-b529-6e28cb6c2bec.png)

**Comment by misaugstad** [comment]
Definitely a good idea, the people page takes forever to load!

**Comment by jonfroehlich** [comment]
We have independent agreement! 🤣 Jae just said this in Slack:

> Part of the reason why the “People” page might be slow is because there are so many people’s image. One thing I’ve seen other labs do is to remove people’s images and to just list their names… Perhaps we can have different sections such as “Undergrad” “PhD” etc and only list alumni’s names…?

**Comment by jonfroehlich** [comment]
This is done.

![image](https://github.com/makeabilitylab/makeabilitylabwebsite/assets/1621749/23cf73ea-c9a8-4383-9426-b2cbe42c7181)
